cinnamon-system-settings@100savage/README.md
gnome-system-monitor@100savage/README.md

cinnamon-system-settings@100savage and gnome-system-monitor@100savage: Update READMEs

---

calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/es.po
cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/es.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/es.po
restart-cinnamon@claudiux/files/restart-cinnamon@claudiux/po/es.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/es.po
send-to-printer@rcalixte/files/send-to-printer@rcalixte/po/es.po
send-with-kdeconnect@rcalixte/files/send-with-kdeconnect@rcalixte/po/es.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/es.po

update spanish translations

---

calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/fi.po
cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/fi.po
gnome-system-monitor@100savage/files/gnome-system-monitor@100savage/po/fi.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fi.po
restart-cinnamon@claudiux/files/restart-cinnamon@claudiux/po/fi.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/fi.po
send-to-printer@rcalixte/files/send-to-printer@rcalixte/po/fi.po
send-with-kdeconnect@rcalixte/files/send-with-kdeconnect@rcalixte/po/fi.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/fi.po

I wrote the Finnish po files for the Cinnamon spices actions section to be published.

Cinnamon spices actions po files in Finnish

---

calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/it.po
cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/it.po
gnome-system-monitor@100savage/files/gnome-system-monitor@100savage/po/it.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/it.po
restart-cinnamon@claudiux/files/restart-cinnamon@claudiux/po/it.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/it.po
send-to-printer@rcalixte/files/send-to-printer@rcalixte/po/it.po
send-with-kdeconnect@rcalixte/files/send-with-kdeconnect@rcalixte/po/it.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/it.po

Hi,
I've added the Italian translations for all available actions.
Have a nice day! :D

Adds new Italian translations

---

calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/hu.po
cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/hu.po
gnome-system-monitor@100savage/files/gnome-system-monitor@100savage/po/hu.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/hu.po
restart-cinnamon@claudiux/files/restart-cinnamon@claudiux/po/hu.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/hu.po
send-to-printer@rcalixte/files/send-to-printer@rcalixte/po/hu.po
send-with-kdeconnect@rcalixte/files/send-with-kdeconnect@rcalixte/po/hu.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/hu.po

The commit contains the hu.po files for the Hungarian translation of the cinnamon spices actions

Hungarian translation for cinnamon spices actions

---

reload-all-desklets@rcalixte/CHANGELOG.md
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/metadata.json
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/da.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/es.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fi.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/hu.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/it.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/reload-all-desklets@rcalixte.pot
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/ru.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.py

Fixes linuxmint/mint21.3-beta#26
cc @haggen88

reload-all-desklets@rcalixte: Remove problematic desklets from reloads

---

create-desktop-shortcut@anaximeno/create-desktop-shortcut@anaximeno.nemo_action.in
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/action.py
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/check.sh
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/metadata.json

Don't show the action in the context menu when inside the desktop folder.

create-desktop-shortcut@anaximeno: add check script

---

reload-all-desklets@rcalixte/CHANGELOG.md
reload-all-desklets@rcalixte/README.md
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/metadata.json
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/da.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/es.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fi.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/hu.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/it.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/pt.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/reload-all-desklets@rcalixte.pot
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/ru.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/tr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.py
reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.nemo_action.in

Closes linuxmint/mint21.3-beta#26

reload-all-desklets@rcalixte: Add a zenity dialog for frozen desklet workaround

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/fi.po

New fi.po in Finnish (create-desktop-shortcut-action)

New create-desktop-shortcut-action in Finnish

---

reload-all-desklets@rcalixte/CHANGELOG.md
reload-all-desklets@rcalixte/README.md
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/metadata.json
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/da.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/es.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fi.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/hu.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/it.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/pt.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/reload-all-desklets@rcalixte.pot
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/ru.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/tr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.py
reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.nemo_action.in

Closes #82, Fixes linuxmint/mint21.3-beta#26

reload-all-desklets@rcalixte: Fix X11 reload with Gtk.Dialog

---

reload-all-desklets@rcalixte/CHANGELOG.md
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/metadata.json
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/da.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/es.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fi.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/hu.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/it.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/pt.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/reload-all-desklets@rcalixte.pot
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/ru.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/tr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.py

* Adjust Gtk.Dialog conditional for X11 and locked desklets
* Fix gtk_main_quit exception

reload-all-desklets@rcalixte: Version 1.3.1

---

reload-all-desklets@rcalixte/CHANGELOG.md
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/metadata.json
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/da.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/es.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fi.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/fr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/hu.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/it.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/pt.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/reload-all-desklets@rcalixte.pot
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/ru.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/tr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.py
reload-all-desklets@rcalixte/reload-all-desklets@rcalixte.nemo_action.in

* Simplify DBus calls
* Add DBus conditions and dependencies
* Add another desklet to avoid restarting

reload-all-desklets@rcalixte: Version 1.4

---

calculate-sha256sum@rcalixte/CHANGELOG.md
calculate-sha256sum@rcalixte/README.md
calculate-sha256sum@rcalixte/calculate-sha256sum@rcalixte.nemo_action.in
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/calculate-sha256sum@rcalixte.sh
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/metadata.json
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/calculate-sha256sum@rcalixte.pot
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/da.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/de.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/es.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/fi.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/fr.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/hu.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/it.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/pt_BR.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/pt_PT.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/ru.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/tr.po

* Add support for multiple files

calculate-sha256sum: Version 1.2

---

calculate-md5sum@schorschii/files/calculate-md5sum@schorschii/po/hu.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/hu.po
compile-run-gcc@anticitizn/files/compile-run-gcc@anticitizn/po/hu.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/hu.po
davinci-audio-adjustment@schorschii/files/davinci-audio-adjustment@schorschii/po/hu.po
image-compressor@schorschii/files/image-compressor@schorschii/po/hu.po
msg-convert@schorschii/files/msg-convert@schorschii/po/hu.po
pdf-compressor@schorschii/files/pdf-compressor@schorschii/po/hu.po
pdf-ocr@schorschii/files/pdf-ocr@schorschii/po/hu.po
quick-desktop-entry@yfabrik/files/quick-desktop-entry@yfabrik/po/hu.po
verify-md5sum@schorschii/files/verify-md5sum@schorschii/po/hu.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/hu.po

Updated Hungarian translation for Cinnamon actions

---

image-compressor@schorschii/files/image-compressor@schorschii/po/fi.po
msg-convert@schorschii/files/msg-convert@schorschii/po/fi.po
pdf-compressor@schorschii/files/pdf-compressor@schorschii/po/fi.po
pdf-ocr@schorschii/files/pdf-ocr@schorschii/po/fi.po

New Finnish language translation packages to cinnamon spices actions

New Finnish language translation packages

---

send-to-printer@rcalixte/send-to-printer@rcalixte.nemo_action.in

send-to-printer@rcalixte: Fix batch printing

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/metadata.json

create-desktop-shortcut@anaximeno: bump version

---

image-compressor@schorschii/image-compressor@schorschii.nemo_action.in
msg-convert@schorschii/msg-convert@schorschii.nemo_action.in
pdf-compressor@schorschii/pdf-compressor@schorschii.nemo_action.in
pdf-ocr@schorschii/pdf-ocr@schorschii.nemo_action.in
validate-spice

* Remove double quotes from existing Actions will fail
cc @schorschii

Update validation to fail on double quotes

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/tr.po

create-desktop-shortcut@anaximeno: Update tr.po

create-desktop-shortcut@anaximeno: Update tr.po

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/create-desktop-shortcut@anaximeno.pot
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/it.po

This is my first time contributing to an open source project, please check I made it all right. It looks like it changed some stuff in the .pot as well when I tried the script, not sure about it, please forgive my incompetence, I'm here to learn.

Added italian .po for create-desktop-shortcut.

---

restart-cinnamon@claudiux/files/restart-cinnamon@claudiux/po/sv.po

restart-cinnamon@claudiux: Create sv.po

---

send-with-kdeconnect@rcalixte/files/send-with-kdeconnect@rcalixte/po/sv.po

send-with-kdeconnect@rcalixte: Create sv.po

---

send-as-attachment@rcalixte/CHANGELOG.md
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/metadata.json
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/da.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/de.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/es.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/fi.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/fr.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/hu.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/it.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/pt_BR.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/pt_PT.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/ru.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/send-as-attachment@rcalixte.pot
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/tr.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/send-as-attachment@rcalixte.py
send-as-attachment@rcalixte/send-as-attachment@rcalixte.nemo_action.in

send-as-attachment@rcalixte: Switch to a Python helper script

---

move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/check.sh
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/metadata.json

Fixes https://github.com/linuxmint/cinnamon-spices-actions/issues/192

move-into-a-new-folder@anaximeno: Hide if user can't write to the current folder

---

move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/check.sh
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/metadata.json

Fix following the previous PR, https://github.com/linuxmint/cinnamon-spices-actions/pull/200.

move-into-a-new-folder@anaximeno: Quote dir name while checking write perms

---

calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/hr.po
calculate-sha512sum@rcalixte/files/calculate-sha512sum@rcalixte/po/hr.po
reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/hr.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/hr.po
send-to-printer@rcalixte/files/send-to-printer@rcalixte/po/hr.po
send-with-kdeconnect@rcalixte/files/send-with-kdeconnect@rcalixte/po/hr.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/hr.po
verify-sha512sum@rcalixte/files/verify-sha512sum@rcalixte/po/hr.po

Added hr translation for all @rcalixte spices

Added hr translation for all @rcalixte spices

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/hr.po

Added hr (Croatian) translation @anaximeno

create-desktop-shortcut@anaximeno: Added hr translation

---

calculate-md5sum@schorschii/files/calculate-md5sum@schorschii/po/hr.po
check-with-virustotal@stilktf/files/check-with-virustotal@stilktf/po/hr.po
cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/hr.po
cinnamon-take-screenshot@duracell80/files/cinnamon-take-screenshot@duracell80/po/hr.po
compile-run-gcc@anticitizn/files/compile-run-gcc@anticitizn/po/hr.po
davinci-audio-adjustment@schorschii/files/davinci-audio-adjustment@schorschii/po/hr.po
download-subtitles@kavalanche/files/download-subtitles@kavalanche/po/hr.po
gnome-system-monitor@100savage/files/gnome-system-monitor@100savage/po/hr.po
image-compressor@schorschii/files/image-compressor@schorschii/po/hr.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/hr.po
msg-convert@schorschii/files/msg-convert@schorschii/po/hr.po
open-in-remote-terminal@mamolinux/files/open-in-remote-terminal@mamolinux/po/hr.po
pdf-compressor@schorschii/files/pdf-compressor@schorschii/po/hr.po
pdf-ocr@schorschii/files/pdf-ocr@schorschii/po/hr.po
peazip-extract-here@BlancoBv/files/peazip-extract-here@BlancoBv/po/hr.po
quick-desktop-entry@yfabrik/files/quick-desktop-entry@yfabrik/po/hr.po
restart-cinnamon@claudiux/files/restart-cinnamon@claudiux/po/hr.po
verify-md5sum@schorschii/files/verify-md5sum@schorschii/po/hr.po
vscode-launcher@vajdao/files/vscode-launcher@vajdao/po/hr.po

All spices translated into Croatian
@rcalixte @schorschii @stilktf @100savage etc.

All spices translated into Croatian

---

move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/sv.po

move-into-a-new-folder@anaximeno: Create sv.po

---

create-shortcut-here@czmisacz/files/create-shortcut-here@czmisacz/action.py

A fix for a small issue inherited from my action.
cc @CZmisaCZ

create-shortcut-here@czmisacz: Fix wrong name formatting for some items

---

create-desktop-shortcut@anaximeno/README.md
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/action.py
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/metadata.json

Add installation instructions, suggestion by @satreks

 create-desktop-shortcut@anaximeno: Add installation instructions

---

image-compressor@schorschii/files/image-compressor@schorschii/po/sv.po

image-compressor@schorschii: Create sv.po

---

send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/sv.po

send-as-attachment@rcalixte: Create sv.po

---

file-shredder@czmisacz/files/file-shredder@czmisacz/po/sv.po

file-shredder@czmisacz: Create sv.po

---

pdf-ocr@schorschii/files/pdf-ocr@schorschii/po/sv.po

pdf-ocr@schorschii: Create sv.po

---

move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/action.py
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/aui.py
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/metadata.json
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/cs.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/de.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/es.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/hr.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/hu.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/it.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/move-into-a-new-folder@anaximeno.pot
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/pt.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/sv.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/text.py
move-into-a-new-folder@anaximeno/move-into-a-new-folder@anaximeno.nemo_action.in

Migrate move-into-a-new-folder@anaximeno to my basic UI toolkit for nemo actions and undepend zenity.

move-into-a-new-folder@anaximeno: Migrate to AUI

---

gnome-system-monitor@100savage/files/gnome-system-monitor@100savage/po/sv.po

gnome-system-monitor@100savage: Create sv.po

---

cinnamon-take-screenshot@duracell80/files/cinnamon-take-screenshot@duracell80/po-sh/lang_sv.txt
cinnamon-take-screenshot@duracell80/files/cinnamon-take-screenshot@duracell80/po/sv.po

cinnamon-take-screenshot@duracell80: Create sv.po

---

paste-into-file@anaximeno/files/paste-into-file@anaximeno/action.py
paste-into-file@anaximeno/files/paste-into-file@anaximeno/aui.py
paste-into-file@anaximeno/files/paste-into-file@anaximeno/metadata.json
paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/es.po
paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/hu.po
paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/paste-into-file@anaximeno.pot
paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/pt.po
paste-into-file@anaximeno/files/paste-into-file@anaximeno/text.py

Now users can choose between overriding the content or append to the end of the file if an existing file is chosen to paste into.

paste-into-file@anaximeno: Allow to choose action if file exists

---

paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/sv.po

paste-into-file@anaximeno: Update sv.po

---

file-shredder@czmisacz/files/file-shredder@czmisacz/action.sh
file-shredder@czmisacz/files/file-shredder@czmisacz/metadata.json
file-shredder@czmisacz/files/file-shredder@czmisacz/po/cs.po
file-shredder@czmisacz/files/file-shredder@czmisacz/po/es.po
file-shredder@czmisacz/files/file-shredder@czmisacz/po/file-shredder@czmisacz.pot
file-shredder@czmisacz/files/file-shredder@czmisacz/po/hu.po
file-shredder@czmisacz/files/file-shredder@czmisacz/po/sv.po

As suggested [here](https://github.com/linuxmint/cinnamon-spices-actions/pull/272) I have added confirmation dialog.

file-shredder@czmisacz: Added confirmation dialog

---

calculate-md5sum@schorschii/files/calculate-md5sum@schorschii/po/fi.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/fi.po
calculate-sha512sum@rcalixte/files/calculate-sha512sum@rcalixte/po/fi.po
check-with-virustotal@stilktf/files/check-with-virustotal@stilktf/po/fi.po
cinnamon-take-screenshot@duracell80/files/cinnamon-take-screenshot@duracell80/po/fi.po
clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/fi.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/fi.po
create-shortcut-here@czmisacz/files/create-shortcut-here@czmisacz/po/fi.po
davinci-audio-adjustment@schorschii/files/davinci-audio-adjustment@schorschii/po/fi.po
download-subtitles@kavalanche/files/download-subtitles@kavalanche/po/fi.po
file-shredder@czmisacz/files/file-shredder@czmisacz/po/fi.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/fi.po
open-in-remote-terminal@mamolinux/files/open-in-remote-terminal@mamolinux/po/fi.po
paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/fi.po
verify-md5sum@schorschii/files/verify-md5sum@schorschii/po/fi.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/fi.po
verify-sha512sum@rcalixte/files/verify-sha512sum@rcalixte/po/fi.po
vscode-launcher@vajdao/files/vscode-launcher@vajdao/po/fi.po
xkill@eson57/files/xkill@eson57/po/fi.po

I have translated using the poedit program. Tested in Mint 21.3.

Add new Finnish language packages

---

calculate-md5sum@schorschii/files/calculate-md5sum@schorschii/po/pt_BR.po

Created the .po file for Brazilian Portuguese and added the translations
@schorschii

calculate-md5sum: Added Brazilian Portuguese translation file 

---

calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/pt_BR.po

Changed Brazilian Portuguese translation to be aligned with the original strings
@rcalixte

calculate-sha256sum: Changed Brazilian Portuguese translation

---

cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/pt_BR.po

cinnamon-system-settings: Added .po file for Brazilian Portuguese

---

clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/pt_BR.po

clone-git-repo: Added .po file for Brazilian Portuguese

---

compile-run-gcc@anticitizn/files/compile-run-gcc@anticitizn/po/pt_BR.po

compile-run-gcc: Added .po file for Brazilian Portuguese

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/pt_BR.po

create-desktop-shortcut: Added .po file for Brazilian Portuguese

---

create-shortcut-here@czmisacz/files/create-shortcut-here@czmisacz/po/pt_BR.po

create-shortcut-here: Added .po file for Brazilian Portuguese

---

davinci-audio-adjustment@schorschii/files/davinci-audio-adjustment@schorschii/po/pt_BR.po

davinci-audio-adjustment: Added .po file for Brazilian Portuguese

---

file-shredder@czmisacz/files/file-shredder@czmisacz/po/pt_BR.po

file-shredder: Added .po file for Brazilian Portuguese

---

gnome-system-monitor@100savage/files/gnome-system-monitor@100savage/po/pt_BR.po

gnome-system-monitor: Added .po file for Brazilian Portuguese

---

image-compressor@schorschii/files/image-compressor@schorschii/po/pt_BR.po

image-compressor: Added .po file for Brazilian Portuguese

---

move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/pt_BR.po

move-into-a-new-folder: Added .po file for Brazilian Portuguese

---

msg-convert@schorschii/files/msg-convert@schorschii/po/pt_BR.po

msg-convert: Added .po file for Brazilian Portuguese

---

open-in-remote-terminal@mamolinux/files/open-in-remote-terminal@mamolinux/po/pt_BR.po

open-in-remote-terminal: Added .po file for Brazilian Portuguese

---

paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/pt_BR.po

paste-into-file: Added .po file for Brazilian Portuguese

---

download-subtitles@kavalanche/files/download-subtitles@kavalanche/po/pt_BR.po

download-subtitles: Added .po file for Brazilian Portuguese

---

move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/action.py
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/aui.py
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/metadata.json

move-into-a-new-folder@anaximeno: Move into a new folder update 1.2.0

---

pdf-compressor@schorschii/files/pdf-compressor@schorschii/po/pt_BR.po

pdf-compressor: Added .po file for Brazilian Portuguese

---

pdf-ocr@schorschii/files/pdf-ocr@schorschii/po/pt_BR.po

pdf-ocr: Added .po file for Brazilian Portuguese

---

peazip-extract-here@BlancoBv/files/peazip-extract-here@BlancoBv/po/pt_BR.po

peazip-extract-here: Added .po file for Brazilian Portuguese

---

quick-desktop-entry@yfabrik/files/quick-desktop-entry@yfabrik/po/pt_BR.po

quick-desktop-entry: Added .po file for Brazilian Portuguese

---

reload-all-desklets@rcalixte/files/reload-all-desklets@rcalixte/po/pt_BR.po

reload-all-desklets: Added .po file for Brazilian Portuguese

---

restart-cinnamon@claudiux/files/restart-cinnamon@claudiux/po/pt_BR.po

restart-cinnamon: Added .po file for Brazilian Portuguese

---

run-in-terminal@alextpedro/files/run-in-terminal@alextpedro/po/pt_BR.po

run-in-terminal: Added .po file for Brazilian Portuguese

---

verify-md5sum@schorschii/files/verify-md5sum@schorschii/po/pt_BR.po

verify-md5sum: Added .po file for Brazilian Portuguese

---

verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/pt_BR.po

verify-sha256sum: Added .po file for Brazilian Portuguese

---

verify-sha512sum@rcalixte/files/verify-sha512sum@rcalixte/po/pt_BR.po

verify-sha512sum: Added .po file for Brazilian Portuguese

---

vscode-launcher@vajdao/files/vscode-launcher@vajdao/po/pt_BR.po

vscode-launcher: Added .po file for Brazilian Portuguese

---

xkill@eson57/files/xkill@eson57/po/pt_BR.po

xkill: Added .po file for Brazilian Portuguese

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/bg_BG.po

Add Bulgarian translation

---

calculate-md5sum@schorschii/files/calculate-md5sum@schorschii/po/zh.po
calculate-sha256sum@rcalixte/files/calculate-sha256sum@rcalixte/po/zh.po
calculate-sha512sum@rcalixte/files/calculate-sha512sum@rcalixte/po/zh.po
cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/zh.po
cinnamon-take-screenshot@duracell80/files/cinnamon-take-screenshot@duracell80/po/zh.po
clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/zh.po
compile-run-gcc@anticitizn/files/compile-run-gcc@anticitizn/po/zh.po
create-shortcut-here@czmisacz/files/create-shortcut-here@czmisacz/po/zh.po

*calculate-md5sum@schorschii
*calculate-sha256sum@rcalixte
*calculate-sha512sum@rcalixte
*cinnamon-system-settings@100savage
*cinnamon-take-screenshot@duracell80
*clone-git-repo@anaximeno
*compile-run-gcc@anticitizn
*create-shortcut-here@czmisacz

Add Chinese translations

---

backup-this-file@h3nr1ke/files/backup-this-file@h3nr1ke/po/zh.po
open-in-intellij-idea@el-amine-404/files/open-in-intellij-idea@el-amine-404/po/zh.po

* backup-this-file@h3nr1ke
* open-in-intellij-idea@el-amine-404

Add Chinese translation

---

open-in-intellij-idea@el-amine-404/files/open-in-intellij-idea@el-amine-404/po/pt_BR.po
webp-to-png@tomunek/files/webp-to-png@tomunek/po/pt_BR.po

The following action were translated
- open-in-intellij-idea@el-amine-404
- webp-to-png@tomunek

Added pt_BR translations

---

backup-this-file@h3nr1ke/files/backup-this-file@h3nr1ke/po/fi.po
cinnamon-take-screenshot@duracell80/files/cinnamon-take-screenshot@duracell80/po/fi.po
clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/fi.po
copy-path-to-clipboard@claudiux/files/copy-path-to-clipboard@claudiux/po/fi.po
image-compressor@schorschii/files/image-compressor@schorschii/po/fi.po
msg-convert@schorschii/files/msg-convert@schorschii/po/fi.po
open-in-intellij-idea@el-amine-404/files/open-in-intellij-idea@el-amine-404/po/fi.po
open-in-remote-terminal@mamolinux/files/open-in-remote-terminal@mamolinux/po/fi.po
pdf-compressor@schorschii/files/pdf-compressor@schorschii/po/fi.po
pdf-ocr@schorschii/files/pdf-ocr@schorschii/po/fi.po
run-in-terminal@alextpedro/files/run-in-terminal@alextpedro/po/fi.po
webp-to-png@tomunek/files/webp-to-png@tomunek/po/fi.po

Some of the translations are updates and a few new translations.

Updated Finnish translations

---

convert-image-format@el-amine-404/files/convert-image-format@el-amine-404/convert-image-format.sh
convert-image-format@el-amine-404/files/convert-image-format@el-amine-404/po/pt.po

convert-image-format@el-amine-404: Bind text domain and text domain and add pt translation

---

send-via-bluetooth@asgharalitaj/files/send-via-bluetooth@asgharalitaj/po/it.po

Hi,
I've added the Italian translations for 2 actions.
Have a nice day :)

Adds Italian translations

---

backup-this-file@h3nr1ke/files/backup-this-file@h3nr1ke/po/eu.po
cinnamon-system-settings@100savage/files/cinnamon-system-settings@100savage/po/eu.po
cinnamon-take-screenshot@duracell80/files/cinnamon-take-screenshot@duracell80/po/eu.po
convert-file@thigschuch/files/convert-file@thigschuch/po/eu.po
convert-image-format@el-amine-404/files/convert-image-format@el-amine-404/po/eu.po
copy-path-to-clipboard@claudiux/files/copy-path-to-clipboard@claudiux/po/eu.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/eu.po
image-compressor@schorschii/files/image-compressor@schorschii/po/eu.po
run-in-terminal@alextpedro/files/run-in-terminal@alextpedro/po/eu.po
send-as-attachment@rcalixte/files/send-as-attachment@rcalixte/po/eu.po
send-to-printer@rcalixte/files/send-to-printer@rcalixte/po/eu.po
send-via-bluetooth@asgharalitaj/files/send-via-bluetooth@asgharalitaj/po/eu.po

Add basque translation

---

copy-path-to-clipboard@claudiux/files/copy-path-to-clipboard@claudiux/po/ca.po
peazip-add-to-archive@xszabo3/files/peazip-add-to-archive@xszabo3/po/ca.po

* copy-path-to-clipboard@claudiux
* peazip-add-to-archive@xszabo3

Update Catalan translations

---

peazip-add-to-archive@xszabo3/files/peazip-add-to-archive@xszabo3/po/es.po

Obs:  For some reason Github was not loading my commits and then released them all at once

peazip-add-to-archive@xszabo3 - add es.po

---

run-in-terminal@alextpedro/README.md

Change links from my personal actions repository to the linuxmint actions repository.

Update README.md to use the links for the linuxmint actions repository.

---

clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/pl.po
clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/ru.po
clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/uk.po

The title says it all :)
@anaximeno

clone-git-repo@anaximeno: Add Ukrainian, Polish, and Russian translations

---

copy-name-to-clipboard@torchipeppo/files/copy-name-to-clipboard@torchipeppo/po/ca.po
link-target-to-tab@mdpenguin/files/link-target-to-tab@mdpenguin/po/ca.po
pdf-cut@ernemir/files/pdf-cut@ernemir/po/ca.po
pdf-rotate@goebbe/files/pdf-rotate@goebbe/po/ca.po
pdf-truncate-batch-print@goebbe/files/pdf-truncate-batch-print@goebbe/po/ca.po
search-path-to-tab@mdpenguin/files/search-path-to-tab@mdpenguin/po/ca.po

* copy-name-to-clipboard@torchipeppo
* link-target-to-tab@mdpenguin
* pdf-cut@ernemir
* pdf-rotate@goebbe
* pdf-truncate-batch-print@goebbe
* search-path-to-tab@mdpenguin

Add Catalan translations

---

pdf-cut@ernemir/CHANGELOG.md
pdf-cut@ernemir/files/pdf-cut@ernemir/pdf-cut.sh

Fixed page range control bug

---

clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/it.po
convert-image-format@el-amine-404/files/convert-image-format@el-amine-404/po/it.po
copy-name-to-clipboard@torchipeppo/files/copy-name-to-clipboard@torchipeppo/po/it.po
copy-path-to-clipboard@claudiux/files/copy-path-to-clipboard@claudiux/po/it.po
install-fonts@anaximeno/files/install-fonts@anaximeno/po/it.po
link-target-to-tab@mdpenguin/files/link-target-to-tab@mdpenguin/po/it.po
pdf-cut@ernemir/files/pdf-cut@ernemir/po/it.po
pdf-rotate@goebbe/files/pdf-rotate@goebbe/po/it.po
pdf-truncate-batch-print@goebbe/files/pdf-truncate-batch-print@goebbe/po/it.po
peazip-add-to-archive@xszabo3/files/peazip-add-to-archive@xszabo3/po/it.po
peazip-extract-here@BlancoBv/files/peazip-extract-here@BlancoBv/po/it.po
peazip-flatpak-convert@xszabo3/files/peazip-flatpak-convert@xszabo3/po/it.po
peazip-flatpak-extract-here@xszabo3/files/peazip-flatpak-extract-here@xszabo3/po/it.po
peazip-flatpak-extract-to-folder@xszabo3/files/peazip-flatpak-extract-to-folder@xszabo3/po/it.po
peazip-flatpak-extract@xszabo3/files/peazip-flatpak-extract@xszabo3/po/it.po
peazip-flatpak-open-as-archive@xszabo3/files/peazip-flatpak-open-as-archive@xszabo3/po/it.po
search-path-to-tab@mdpenguin/files/search-path-to-tab@mdpenguin/po/it.po

Hello,
I've updated and added some new Italian translations for Cinnamon Spices Actions.
Have a nice day!

Add and update Italian translations

---

link-target-to-tab@mdpenguin/files/link-target-to-tab@mdpenguin/metadata.json

Bump version for link-target-to-tab@mdpenguin to reflect changes from #586

link-target-to-tab@mdpenguin: bump version number

---

create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/metadata.json
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/bg_BG.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/ca.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/create-desktop-shortcut@anaximeno.pot
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/cs.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/da.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/de.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/es.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/eu.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/fi.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/fr.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/hr.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/hu.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/it.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/nl.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/pt.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/pt_BR.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/ru.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/tr.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/po/zh_CN.po
create-desktop-shortcut@anaximeno/files/create-desktop-shortcut@anaximeno/text.py

Update name for better consistency between translations.

create-desktop-shortcut@anaximeno: Update naming

---

copy-name-to-clipboard@torchipeppo/CHANGELOG.md
copy-name-to-clipboard@torchipeppo/files/copy-name-to-clipboard@torchipeppo/metadata.json

[copy-name-to-clipboard@torchipeppo] Housekeeping: bump version number

---

clone-git-repo@anaximeno/files/clone-git-repo@anaximeno/po/fi.po
compile-run-gcc@anticitizn/files/compile-run-gcc@anticitizn/po/fi.po
convert-file@thigschuch/files/convert-file@thigschuch/po/fi.po
convert-image-format@el-amine-404/files/convert-image-format@el-amine-404/po/fi.po
download-subtitles@kavalanche/files/download-subtitles@kavalanche/po/fi.po
link-target-to-tab@mdpenguin/files/link-target-to-tab@mdpenguin/po/fi.po
make-file-conceal@RutarAndriy/files/make-file-conceal@RutarAndriy/po/fi.po
make-file-executable@RutarAndriy/files/make-file-executable@RutarAndriy/po/fi.po
make-file-reveal@RutarAndriy/files/make-file-reveal@RutarAndriy/po/fi.po
make-file-unexecutable@RutarAndriy/files/make-file-unexecutable@RutarAndriy/po/fi.po
move-into-a-new-folder@anaximeno/files/move-into-a-new-folder@anaximeno/po/fi.po
msg-convert@schorschii/files/msg-convert@schorschii/po/fi.po
paste-into-file@anaximeno/files/paste-into-file@anaximeno/po/fi.po
pdf-cut@ernemir/files/pdf-cut@ernemir/po/fi.po
pdf-rotate@goebbe/files/pdf-rotate@goebbe/po/fi.po
pdf-truncate-batch-print@goebbe/files/pdf-truncate-batch-print@goebbe/po/fi.po
peazip-add-to-archive@xszabo3/files/peazip-add-to-archive@xszabo3/po/fi.po
search-path-to-tab@mdpenguin/files/search-path-to-tab@mdpenguin/po/fi.po
send-with-kdeconnect@rcalixte/files/send-with-kdeconnect@rcalixte/po/fi.po
verify-md5sum@schorschii/files/verify-md5sum@schorschii/po/fi.po
verify-sha256sum@rcalixte/files/verify-sha256sum@rcalixte/po/fi.po
verify-sha512sum@rcalixte/files/verify-sha512sum@rcalixte/po/fi.po
webp-to-png@tomunek/files/webp-to-png@tomunek/po/fi.po

Finnish language packs and improvements

Finnish language pack
